@startuml

title Channels

namespace channel <<rectangle>> {

    json channel.Supergroup {
        "id" : 2200055731,
        "isChannel": true,
        "isForum": false,
        "hasLinkedChat": true,
        "hasDirectMessagesGroup": false,
        "isDirectMessagesGroup": false
    }

    json channel.SupergroupFullInfo {
        "description" : "channel with discussion chat",
        "linkedChatId" : -1002200816075,
        "directMessagesChatId": 0

    }

    json channel.Chat {
        "id" : -1002200055731,
        "type": {
            "_type" : "ChatTypeSupergroup",
            "supergroupId": 2200055731,
            "isChannel": true
        }
    }
    
    Supergroup ->SupergroupFullInfo : getSupergroupFullInfo
}  

namespace discussionChat <<rectangle>> {
    json discussionChat.Supergroup {
        "id" : 2200816075,
        "isChannel": false,
        "isForum": false,
        "hasLinkedChat": true,
        "hasDirectMessagesGroup": false,
        "isDirectMessagesGroup": false
    }

    json discussionChat.SupergroupFullInfo {
        "description" : "Discussion chat for lvtest2",
        "linkedChatId" : -1002200055731,
        "directMessagesChatId": 0

    }

    json discussionChat.Chat {
        "id" : -1002200816075,
        "type": {
            "_type" : "ChatTypeSupergroup",
            "supergroupId": 2200816075,
            "isChannel": false
        }
    }

    Supergroup ->SupergroupFullInfo : getSupergroupFullInfo

}


channel -[hidden]-> discussionChat

discussionChat.SupergroupFullInfo -> channel.Chat

@enduml
